### ISSUE TITLE
Documentation amendments

### ISSUE THREAD

**Issue by mgdde** [Befaco/burst#1]
Hi!

While trying to build the code for BURST I encountered the following problems:
Installing RotaryEncoder (as documented) did not seem to have any effect. However to get it to compile I also had to install ClickEncoder (found via the muxlicer github page) as well as the Libraries TimerOne and Bounce2.

I understand the Processor to compile to is an ATmega328P. Is there a special board that I should select? I currently use Arduino Nano.

I kindly ask to amend the documentation to include this information.

Kind regards,
Michael

**Comment by xustafu** [comment]
Done!
Thanks a bunch for the feedback.
